In [12]:
from nn import NeuralNetwork
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import numpy as np

In [57]:
#Load and split digits dataset
split_percent = .33

digits = load_digits()
y = digits['target']
X = digits['data']
# print(X.T.shape)
# print(np.array([y]).shape)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=split_percent, random_state=42)

#Reshape dataset to fit convention used in implementation of neural net
X_train = X_train.T 
X_val = X_val.T
y_train = np.array([y_train])
y_val = np.array([y_val])
print(X_train.shape)


(64, 1203)


Rationale for hyperparameter choice:

In [55]:
#Define hyperparams
nn_arch = [{'input_dim': 64, 'output_dim': 16, 'activation': 'relu'}, {'input_dim': 16, 'output_dim': 64, 'activation': 'sigmoid'}]
lr = 0.00001
seed = 1
batch_size = 500
epochs = 1000
loss_function = 'mse'

In [54]:
autoencoder = NeuralNetwork(nn_arch, lr, seed, batch_size, epochs, loss_function)
autoencoder._param_dict['W1'].shape

(16, 64)

In [56]:
#Train autoencoder using digits dataset
autoencoder = NeuralNetwork(nn_arch, lr, seed, batch_size, epochs, loss_function)
train_loss, val_loss = autoencoder.fit(X_train, y_train, X_val, y_val)

#Plot losses
epochs = np.linspace(1, len(train_loss), len(train_loss))
fig,axs = plt.subplot(2,1)
axs[0,1].plot(epochs, train_loss)
axs[0,1].set_title('Training Loss')
axs[0,1].set_xlabel('Epoch')

axs[1,1].plot(epochs, val_loss)
axs[1,1].set_title('Validation Loss')
axs[1,1].set_xlabel('Epoch')
plt.show()

ValueError: shapes (16,64) and (1,1203,64) not aligned: 64 (dim 1) != 1203 (dim 1)

In [72]:
def fit(X_train,y_train,X_val,y_val):

    epochs = 0
    per_epoch_loss_train = []
    per_epoch_loss_val = []

    while epochs < 1:
        epochs += 1

        #Shuffle training set
        shuffled_indices = np.linspace(0, X_train.shape[1]-1, X_train.shape[1])
        np.random.shuffle(shuffled_indices)
        X_train = np.array([X_train[:, int(i)] for i in shuffled_indices]).T
        y_train = np.array([y_train[:, int(i)] for i in shuffled_indices]).T
        print(X_train, X_train.shape)
        print(y_train, y_train.shape)
        print('')

        #Split training set into batches
        num_batches = int(X_train.shape[1]/300) + 1
        print(num_batches)
        X_batch = [i.T for i in np.array_split(X_train.T, num_batches)]
        y_batch = [i.T for i in np.array_split(y_train.T, num_batches)]
        
        for X_train, y_train in zip(X_batch, y_batch):
            print(X_train.shape)
            print(y_train.shape)
            print('')
            

        #Generate empty lists to hold losses for batches
        training_losses = []
        validation_losses = []

#         for X_train, y_train in zip(X_batch, y_batch):
#             training_output, training_cache = self.forward(X_batch) #forward pass of training and validation set
#             val_output, val_cache = self.forward(X_val)

#             training_losses.append(self._loss_function(y_train, training_output, self._loss_func)) #record training and validation losses
#             validation_losses.append(self._loss_function(y_val, val_output))

#             grad_dict = backprop(y_train, training_output) #backward pass
#             self._update_params(grad_dict) #update weights and biases

#         per_epoch_loss_train.append(np.mean(np.array(training_losses)))
#         per_epoch_loss_val.append(np.mean(np.array(validation_losses)))

    return 

fit(X_train,y_train,X_val,y_val)


[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0. 10.  1. ...  4. 10.  0.]
 ...
 [ 0.  1. 11. ...  0.  8.  4.]
 [ 0.  0.  1. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]] (64, 1203)
[[4 8 6 ... 7 9 1]] (1, 1203)

5
(64, 241)
(1, 241)

(64, 241)
(1, 241)

(64, 241)
(1, 241)

(64, 240)
(1, 240)

(64, 240)
(1, 240)

